### PR TITLE
Check moderation exception

### PR DESCRIPTION
**Pull request by chaws**
We've added two more exception handlers for the cases in which the user needs email confirmation and when approval is required by the list's administrator

### CODE REVIEW

**Comment by seocam** [comment]
Any chance to get tests for this? :)

**Comment by seocam** [comment]
@chaws since that's an API the status codes are more important than the actual messages. Prior to this merge request we had one msg for each status code but now looks like we can have more. In that case I would define a list of codes so the application can define the messages in their own language. For example: `invalid-address`, `banned`, `already-member`, etc...

Besides that this is a restful API so we also have to return coherent status codes and in your changes in you are removing all codes previously defined.

Last but not least, make sure your changes don't break backwards compatibility!

**Comment by chaws** [comment]
@seocam , We've rolled back those HTTP codes and created a new apiv2, which responds to '/v2/' requests. This way we make sure it won't break the API for older users. Also, we've created a list of error codes, which is being interpreted on Colab.

**Comment by seocam** [comment]
@chaws I've pushed your code to own `our check_moderation_exception` branch and I've added you as developer in this repo. Let's continue development there. Cheers!

**Comment by seocam** [comment]
Closed in favor of #8

**Pull request closed without merging**
