### PR TITLE
Apiv2

### PR DESCRIPTION
**Pull request by seocam**
Moving #7 to here.

### CODE REVIEW

**Comment by seocam** [comment]
@chaws now we have a setup that allows us to test you just have to make sure docker is installed on your environment (because we are relying on docker I had to move tests from Travis to CircleCI).

Take a look on the tests we already have so we can start write new ones. The mailman data for tests will leave inside the container so if you need to "insert" more data we have to modify the `Dockerfile` inside the tests directory.

**Comment by chaws** [comment]
@seocam gotcha! Just one thing though: I moved the creating list stuff to inside of the test suite classes, this way Dockerfile stays as simple as possible. Note: I had to rebuilt my local docker image after that.
FYI: So far there are tests for subscription for apiv2 only, we're working to cover all of it.

**Comment by lucaskanashiro** [comment]
I already reviewed this PR, I requested some improvements in tests documentation and it is done by @chaws . I tested all the functionalities locally and everything works well. IMO, It is ready to be merged.

R+

**Comment by seocam** [comment]
Thanks all! :+1:

**Pull request merged**
